name: Android CI (legacy)

on: 
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  #v4.3.1
      with:
        submodules: recursive
        persist-credentials: false

    - name: Setup gradle.properties (legacy)
      run: |
        echo "org.gradle.jvmargs=-Xmx2048m" > gradle.properties
        echo "android.compileVersion = 28" >> gradle.properties
        echo "android.targetVersion = 28" >> gradle.properties
        echo "android.useAndroidX = false" >> gradle.properties
        echo "android.enableJetifier = false" >> gradle.properties  

    - name: Setup gradle-wrapper.properties (legacy)
      run: |
        echo "distributionBase=GRADLE_USER_HOME" > ./gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> ./gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> ./gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> ./gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> ./gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-bin.zip" >> ./gradle/wrapper/gradle-wrapper.properties
        echo "distributionSha256Sum=1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80d" >> ./gradle/wrapper/gradle-wrapper.properties
        
    - name: Setup JDK 11
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9  #v4.8.0
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@748248ddd2a24f49513d8f472f81c3a07d4d50e1  #v4.4.4
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  #v4.3.0
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
    
    - name: Build with Gradle
      run: ./gradlew assembleLegacyDebug
    
    - name: Build with Gradle (Unit tests)
      run: ./gradlew testLegacyRelease
    
    - name: Build with Gradle (lintVitalRelease)
      run: ./gradlew lintVitalLegacyRelease
    
    - name: Upload artifacts (debug apk)
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  #v4.6.2
      with:
        name: app
        path: app/build/outputs/apk/legacy/release/app-legacy-release-unsigned.apk
        
    - name: Upload artifacts (lint results)
      if: success() || failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  #v4.6.2
      with:
        name: lint-results
        path: app/build/reports/lint-results-legacyRelease-fatal.html

    - name: Upload artifacts (merge report)
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: manifest-merger-report
        path: app/build/outputs/logs/manifest-merger-legacy-release-report.html

    - name: Upload artifacts (test results)
      if: success() || failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  #v4.6.2
      with:
        name: test-results
        path: app/build/reports/tests/testLegacyReleaseUnitTest/
