name: Publish nightly build

on: 
  workflow_dispatch:
  push:
    branches:
      - nightly-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: nightly-build

    - name: set up JDK 8.0.422+5
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8.0.422+5'

    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v4
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - uses: actions/cache@v4
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
    
    - name: Build nightly debug
      run: ./gradlew assembleNightlyDebug

    #- name: Setup F-Droid Server (apt-get)
    #  run: |
    #    sudo add-apt-repository ppa:fdroid/fdroidserver
    #    sudo apt-get update
    #    sudo apt-get install apksigner fdroidserver --no-install-recommends
      
    - name: Publish nightly debug
      run: |
        python -m venv fdroidserver-env 
        . fdroidserver-env/bin/activate
        pip install git+https://github.com/forrestguice/fdroidserver.git
        fdroid nightly --archive-older 10
      env:
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
